runtime: nodejs14
default_expiration: '300d'
automatic_scaling:
  max_instances: 1
inbound_services:
  - warmup
handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
