name: Deploy cloud functions
on:
  push:
    paths:
      - .github/workflows/deploy-functions.yml
      - packages/functions/**
      - packages/shared/src/i18n/**
      - yarn.lock
    branches:
      - master

jobs:
  cloudfunctions:
    name: Building cloud functions
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        function:
          [
            translate,
            safetyLevelCalculatorJob,
            statsAggregatorJob,
            emailForwarder,
          ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - run: yarn build
        working-directory: ./packages/functions
      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: ${{ matrix.function }}
          runtime: nodejs14
          credentials: ${{ secrets.GCP_SA_KEY }}
