name: Deploy cloud functions
on:
  push:
    paths:
      - .github/workflows/deploy-functions.yml
      - packages/functions/**
      - packages/shared/src/i18n/**
      - yarn.lock
    branches:
      - master


jobs:
  cloudfunctions:
    name: Building cloud functions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - uses: w9jds/firebase-action@a17f996b089638653d57c7aa85d0763e256b13fb
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Warmup
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://us-central1-openfortravel.cloudfunctions.net/warmer'
          method: 'GET'
