name: Deploy cloud functions
on:
  push:
    paths:
      - .github/workflows/deploy-functions.yml
      - packages/functions/**
      - packages/shared/src/i18n/**
    branches:
      - master

jobs:
  cloudfunctions:
    name: Building cloud functions
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        function: [ emailForwarder ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Restore yarn workspaces
        id: yarn-cache
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-${{ matrix.function }}
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --ignore-platform --frozen-lockfile
      - run: yarn build
        working-directory: ./packages/functions
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
