name: Front deploy
on:
  push:
    paths:
      - .github/workflows/deploy-front.yml
      - packages/front/**
      - packages/shared/**
    branches:
      - master

jobs:
  release:
    name: Compiling a new frontend build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - run: yarn build
        working-directory: ./packages/front
      - id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          working_directory: ./packages/front/dist/ssr
      - id: upload-files
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          path: ./packages/front/dist/ssr/www
          destination: cdn.openfortravel.org/www
          parent: false
      - name: Purge cache
        uses: nathanvaughn/actions-cloudflare-purge@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_AUTH_KEY: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
