name: Deploy cloud functions
on:
  push:
    paths:
      - .github/workflows/deploy-functions.yml
      - packages/functions/**
      - packages/shared/src/i18n/**
    branches:
      - master

jobs:
  cloudfunctions:
    name: Building cloud functions
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        function: [ translate, safetyLevelCalculatorJob, statsAggregatorJob, emailForwarder ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - run: yarn build
        working-directory: ./packages/functions
      - uses: w9jds/firebase-action@a17f996b089638653d57c7aa85d0763e256b13fb
        with:
          args: deploy --only functions:${{ matrix.function }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
